### ISSUE TITLE
Export CMake config

### ISSUE THREAD

**Issue by aljazerzen** [apache/arrow-nanoarrow#350]
When trying to use this library from another CMake project, I've noticed that this project does not export CMake config.

I know that this library is meant to be vendored/bundled with my project, but in my case, this is quite undesirable.

So I've created a patch to export the config here: https://github.com/aljazerzen/arrow-nanoarrow-nix/blob/main/0001-patch.patch

I'm relatively new to CMake, so this issue is mostly about "i this a good idea" and "why not?"

**Comment by assignUser** [comment]
Yes, exporting a `nanoarrowConfig.cmake` is the 'modern CMake' way to make you lib usable by other projects. I can have a look at the patch/turn it into a pr (feel free to that as well @aljazerzen!) but I'll have to read up on the details a bit. As a victim of bad configs I want to make it right :D (e.g. always including targets is bad when using fetchContent because the targets then already exist and clash).

**Comment by aljazerzen** [comment]
I can open the PR, I thought there was a reason this was not done in the first place.
